language: python
sudo: false
env:
  - TOXENV=py27
addons:
  apt:
    packages:
    - libgmp3-dev
install:
  - pip install tox
  - pip install coveralls
script: tox -- --ignore hydrachain/tests/test_sim_failures.py --ignore hydrachain/tests/test_sim_syncing.py
after_success: coveralls
