language: python
sudo: required
services:
  - docker
env:
  global:
  - DOCKER_EMAIL=docker@hydrachain.com
  - DOCKER_USERNAME=hydrachain
  - secure: Rr+meswIU5zxFWscvMTfumD8Fj23lAaWIQuf2REo9NefTpOUvS3CFaZY/sTFZmUybV/IGSvRXZsQoYxYlrNCsTFqwQh5RXft+A9XjrzK8EPQPxugVROoRaKNrgrCKvfy/4mup2bvCz6xp0EmFILZteMTMoveI8FOJYdEmypHpwc9/HrgB6iGFcH8EB1Ny1kXKjHmubF3jnNtsTmxciFc2+ZuC4yVa7aAZU6DMWK72/tWN6qlR5sTY11nkcuWBI/ot4niAuSkWp4RYhXHPoVeewj+0gWNBWejzID6NWK6+tLUu917+xrmjKt30Whjva3+jsNiKVdBsNuDC9M7AXViBedmfzFaRUThotM9dgqVovG6RKW3Ybdqk4cQZldK3DYOF7uVuZ9CujOlf9zYIuGv6sUihd2j6jxLEgDqpC9yumZUBqAHUqegOUizybINNhpIhcQU83ynceaUARXsPdc6JFZziY9RsjNOFkRwRKo+O7o2OfvnA9XSkIWPF8hnt4hrXHdzuzLKqgbR6spiUczuEhosjf2tNk6KlSFk0+K1vx/lx0jd9GoCKdsO/MGnAmh5M0g2OFW1vaj1/td5tQh06qFiIFULlDfSSdDtH0rNUMTRVbiGDF6NzuECYHZ23s2zIMZAOpVWHlItWlG1faBbkKz9UV0P3lqv2bp5CAuAXqk=
  matrix:
  - TOXENV=py27
addons:
  apt:
    packages:
    - libgmp3-dev
install:
  - pip install tox
  - pip install coveralls
script: tox -- --ignore hydrachain/tests/test_sim_failures.py --ignore hydrachain/tests/test_sim_syncing.py
after_success: 
  - coveralls
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t hydrachain/hydrachain:${TRAVIS_TAG:-develop} .
  - docker push hydrachain/hydrachain:${TRAVIS_TAG:-develop}
deploy:
  provider: pypi
  user: ethereum_pypi_automated
  password:
    secure: "vO6kAkkpdqQz2+Le7aowcIkYHyvQzuNaL35c8ciHzmT2VdeGeCsDBGyJ8RYqITQruwfVzUsKsNjfCXBTcYan3e1vPpG9KKrkxB/Zy6KcNJmd+SL9n2tB6TVFr1ojxnRJgIzFBxbA1FnyY0aodwnMW2bJBlKxFIKJiKVjK6GGDl11wrMsudFFnvs3LkrPO9tr1plmN1xvVTNLzy0UmHjx6lmtjtZ/HMbx635WnFj5NnzdeMK07XD59HEuOYVvQ7BQua2cuCevFbXmSAxHJsDPZuhzYHkEfj+jPhKbS1MyTqD5W72ex2oPRmPlvvnOn01750IkSFSyO0lnZIv1wJuZ3+Y+49Q5XrFBAsuC4bqk1uOVL5hU37b2oDBIunJLQYEP1tn7TibVbv51iOolzx193tRR7KcbyU+pIqdP4a6rWDXT+PRada2JemX/Bx4G5hn9dXc4SmLP0+t7lcYpe/fTLQCGYsLNBbJv7iJdTuOeySX8Dlq9GYBMGreilDwIp5T4eqT4mhc25ZaXRel2HdqQSzie8SM88Sempn1V3uQkvQSUZ/PcwDwrG8wLK37BubaW0qVAZ5Zfkv1Q+pnVd7OkTEU+GgdOST6H3WGKVSO0fs/vLFYhQN0273IqM3Uuh3+s5h/sbGWfXqPMS8lu6febpglBCAxvkgKjwQ0in2S3Fo8="
  on:
    tags: true
    repo: HydraChain/hydrachain
    branch: develop
  distributions: "sdist bdist_wheel"
after_deploy:
  - docker tag hydrachain/hydrachain:$TRAVIS_TAG hydrachain/hydrachain:latest
  - docker push hydrachain/hydrachain:latest
